-------------------------------------------------------------------------------
--  Data/Factions/ArgentDawn.lua -- Argent Dawn in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("ArgentDawn", {
    id = 529, name = "Argent Dawn", tab = "reputation",
    zone = "Eastern Plaguelands",
    quartermaster = { name = "Quartermaster Miranda Breechlock", map = 1423, x = 81.4, y = 60 },
    dungeons = { "Stratholme", "Scholomance" },
    maps = { 1422, 1423 },
    turnins = {
        { name = "Minion's Scourgestones", rep = 25, level = 55, takes = { 12840, 20 },
            quests = {
                { 5402, "A", "Western Plaguelands - Argent Officer Pureheart (43, 83.6)", 1422, 43, 83.6 },
                { 5408, "H", "Tirisfal Glades - Argent Officer Garush (83.2, 68.4)", 1420, 83.2, 68.4 },
                { 5510, "B", "Eastern Plaguelands - Duke Nicholas Zverenhoff (81.4, 59.8)", 1423, 81.4, 59.8 },
            },
            from = {
                { "Western Plaguelands", 20, "Blighted Zombie", "Festering Ghoul", "Fetid Zombie", "Foulmane", "Freezing Ghoul", "Hungering Wraith" },
                { "Eastern Plaguelands", 20, "Cannibal Ghoul", "Crypt Fiend", "Crypt Horror", "Crypt Walker", "Cursed Mage", "Dark Caster" },
            },
        },
        { name = "Invader's Scourgestones", rep = 25, level = 55, takes = { 12841, 10 },
            quests = {
                { 5403, "A", "Western Plaguelands - Argent Officer Pureheart (43, 83.6)", 1422, 43, 83.6 },
                { 5407, "H", "Tirisfal Glades - Argent Officer Garush (83.2, 68.4)", 1420, 83.2, 68.4 },
                { 5509, "B", "Eastern Plaguelands - Duke Nicholas Zverenhoff (81.4, 59.8)", 1423, 81.4, 59.8 },
            },
            from = {
                { "Western Plaguelands", 9, "Cauldron Lord Bilemaw", "Cauldron Lord Malvinious", "Cauldron Lord Razarch", "Cauldron Lord Soulwrath", "Flesh Golem", "Haunting Vision" },
                { "Eastern Plaguelands", 20, "Abomination", "Bone Witch", "Crypt Slayer", "Dark Adept", "Death Singer", "Diseased Flayer" },
            },
        },
        { name = "Corruptor's Scourgestones", rep = 25, level = 55, takes = { 12843, 1 },
            quests = {
                { 5404, "A", "Western Plaguelands - Argent Officer Pureheart (43, 83.6)", 1422, 43, 83.6 },
                { 5406, "H", "Tirisfal Glades - Argent Officer Garush (83.2, 68.4)", 1420, 83.2, 68.4 },
                { 5508, "B", "Eastern Plaguelands - Duke Nicholas Zverenhoff (81.4, 59.8)", 1423, 81.4, 59.8 },
            },
            from = {
                { "Western Plaguelands", 2, "Araj the Summoner", "Putridius" },
                { "Eastern Plaguelands", 4, "Gish the Unmoving", "Hed'mush the Rotting", "Lord Darkscythe", "Shadow of Doom" },
            },
        },
        { name = "Felstone Field Cauldron", rep = 25, level = 53, takes = { 13320, 1, 13357, 1, 14047, 6 },
            quests = {
                { 5218, "B", "Western Plaguelands - Scourge Cauldron (37.2, 56.9)", 1422, 37.2, 56.9 },
            },
            from = {
                { "Western Plaguelands", 57, "Araj the Summoner", "Blighted Zombie", "Cauldron Lord Malvinious", "Cauldron Lord Razarch", "Cavalier Durgen", "Crimson Elite" },
            },
        },
        { name = "Dalson's Tears Cauldron", rep = 25, level = 55, takes = { 13320, 1, 13356, 1, 14047, 5 },
            quests = {
                { 5221, "B", "Western Plaguelands - Scourge Cauldron (46.2, 52)", 1422, 46.2, 52 },
            },
            from = {
                { "Western Plaguelands", 57, "Araj the Summoner", "Blighted Zombie", "Cauldron Lord Bilemaw", "Cavalier Durgen", "Crimson Elite", "Fallen Hero" },
            },
        },
        { name = "Writhing Haunt Cauldron", rep = 25, level = 55, takes = { 13320, 1, 13356, 1, 14047, 5 },
            quests = {
                { 5224, "B", "Western Plaguelands - Scourge Cauldron (53, 65.7)", 1422, 53, 65.7 },
            },
            from = {
                { "Western Plaguelands", 57, "Araj the Summoner", "Blighted Zombie", "Cauldron Lord Bilemaw", "Cavalier Durgen", "Crimson Elite", "Fallen Hero" },
            },
        },
        { name = "Gahrron's Withering Cauldron", rep = 25, level = 58, takes = { 13320, 1, 13354, 1, 14047, 4 },
            quests = {
                { 5227, "B", "Western Plaguelands - Scourge Cauldron (62.5, 58.6)", 1422, 62.5, 58.6 },
            },
            from = {
                { "Western Plaguelands", 56, "Araj the Summoner", "Blighted Zombie", "Cauldron Lord Soulwrath", "Cavalier Durgen", "Crimson Elite", "Fallen Hero" },
            },
        },
    },
    tiers = {
        { standing = 5, items = { 13724 } },
        { standing = 6, items = { 13482, 227813, 19203, 19216, 19328, 19442, 19446, 227896, 1164, 22014 } },
        { standing = 7, items = { 12698, 13810, 13813, 22704, 19205, 19217, 19329, 19447, 227895, 227897 } },
        { standing = 8, items = { 22703 } },
    },
    prices = {
        [12698] = 22000,
        [13482] = 15000,
        [13724] = 6000,
        [13810] = 6000,
        [13813] = 6000,
        [19203] = 22000,
        [19205] = 40000,
        [19216] = 22000,
        [19217] = 40000,
        [19328] = 22000,
        [19329] = 40000,
        [19442] = 100000,
        [19446] = 30000,
        [19447] = 60000,
        [22014] = 1333333,
        [22703] = 150000,
        [22704] = 150000,
        [227895] = 40000,
        [227896] = 22000,
        [227897] = 40000,
    },
})
