-------------------------------------------------------------------------------
--  Data/Factions/AzerothCommerceAuthority.lua -- Azeroth Commerce Authority in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("AzerothCommerceAuthority", {
    id = 2586, name = "Azeroth Commerce Authority", tab = "reputation",
    zone = "Redridge Mountains",
    new = true,
    quartermaster = { name = "Tamelyn Aldridge", map = 1433, x = 10.4, y = 71.4 },
    maps = { 1433 },
    tiers = {
        { standing = 6, items = { 270888 } },
        { standing = 8, items = { 262765, 280449 } },
    },
    prices = {
        [262765] = 50000,
        [280449] = 50000,
    },
})
