-------------------------------------------------------------------------------
--  Data/Factions/BroodOfNozdormu.lua -- Brood of Nozdormu in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("BroodOfNozdormu", {
    id = 910, name = "Brood of Nozdormu", tab = "reputation",
    zone = "Tanaris",
    unreleased = true,
    maps = { 1446 },
    tiers = {
        { standing = 4, items = { 21196, 21201, 21206, 234016, 234017, 234018, 234019, 234198, 234440, 234968 } },
        { standing = 5, items = { 21197, 21202, 21207, 234020, 234021, 234022, 234023, 234199, 234439, 234967 } },
        { standing = 6, items = { 21198, 21203, 21208, 234024, 234025, 234026, 234027, 234200, 234438, 234966 } },
        { standing = 7, items = { 21199, 21204, 21209, 234028, 234029, 234030, 234031, 234201, 234437, 234965 } },
        { standing = 8, items = { 21200, 21205, 21210, 234032, 234033, 234034, 234035, 234202, 234436, 234964 } },
    },
})
