-------------------------------------------------------------------------------
--  Data/Factions/CenarionCircle.lua -- Cenarion Circle in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("CenarionCircle", {
    id = 609, name = "Cenarion Circle", tab = "reputation",
    zone = "Silithus",
    quartermaster = { name = "Kania", map = 1451, x = 52, y = 39.4 },
    maps = { 1450, 1451 },
    turnins = {
        { name = "Encrypted Twilight Texts", rep = 100, level = 60, takes = { 20404, 10 },
            quests = {
                { 8319, "B", "Silithus - Bor Wildmane (48.6, 37.6)", 1451, 48.6, 37.6 },
            },
            from = {
                { "Silithus", 10, "Twilight Avenger", "Twilight Flamereaver", "Twilight Geolord", "Twilight Lord Everun", "Twilight Marauder", "Twilight Marauder Morna" },
            },
        },
        { name = "Abyssal Crests", rep = 50, level = 60, takes = { 20513, 3 },
            quests = {
                { 8362, "B", "Silithus - Bor Wildmane (48.6, 37.6)", 1451, 48.6, 37.6 },
            },
            from = {
                { "Silithus", 4, "Azure Templar", "Crimson Templar", "Earthen Templar", "Hoary Templar" },
            },
        },
        { name = "Abyssal Signets", rep = 100, level = 60, takes = { 20514, 3 },
            quests = {
                { 8363, "B", "Silithus - Bor Wildmane (48.6, 37.6)", 1451, 48.6, 37.6 },
            },
            from = {
                { "Silithus", 4, "The Duke of Cynders", "The Duke of Fathoms", "The Duke of Shards", "The Duke of Zephyrs" },
            },
        },
        { name = "Abyssal Scepters", rep = 150, level = 60, takes = { 20515, 3 },
            quests = {
                { 8364, "B", "Silithus - Bor Wildmane (48.6, 37.6)", 1451, 48.6, 37.6 },
            },
            from = {
                { "Silithus", 4, "Baron Kazum", "High Marshal Whirlaxis", "Lord Skwol", "Prince Skaldrenox" },
            },
        },
        { name = "The Four Dukes", rep = 100, level = 60, takes = { 20948, 1 },
            quests = {
                { 8538, "B", "Silithus - Commander Mar'alith (49.2, 34.2)", 1451, 49.2, 34.2 },
            },
        },
    },
    tiers = {
        { standing = 5, items = { 275580, 275583, 275586, 275589, 275592, 275595, 275598, 275601, 234271, 234272, 20732, 22772, 22310, 229897 } },
        { standing = 6, items = { 275581, 275582, 275584, 275585, 275587, 275588, 275590, 275591, 275593, 275594, 275596, 275597, 275599, 275600, 275602, 275603, 20733, 22773 } },
        { standing = 7, items = { 22219, 22683, 22774, 22312 } },
        { standing = 8, items = { 22221 } },
    },
    prices = {
        [20732] = 100000,
        [20733] = 100000,
        [22219] = 50000,
        [22221] = 80000,
        [22310] = 20000,
        [22312] = 50000,
        [22683] = 90000,
        [22772] = 50000,
        [22773] = 50000,
        [22774] = 50000,
        [229897] = 3000,
        [234271] = 100000,
        [234272] = 50000,
        [275580] = 75000,
        [275581] = 75000,
        [275582] = 75000,
        [275583] = 75000,
        [275584] = 75000,
        [275585] = 75000,
        [275586] = 75000,
        [275587] = 75000,
        [275588] = 75000,
        [275589] = 75000,
        [275590] = 75000,
        [275591] = 75000,
        [275592] = 75000,
        [275593] = 75000,
        [275594] = 75000,
        [275595] = 75000,
        [275596] = 75000,
        [275597] = 75000,
        [275598] = 75000,
        [275599] = 75000,
        [275600] = 75000,
        [275601] = 75000,
        [275602] = 75000,
        [275603] = 75000,
    },
})
