-------------------------------------------------------------------------------
--  Data/Factions/DarkspearTrolls.lua -- Darkspear Trolls in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("DarkspearTrolls", {
    id = 530, name = "Darkspear Trolls", tab = "reputation",
    group = "Cities",
    zone = "Orgrimmar",
    side = "Horde",
    maps = { 1411, 1454 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7837, "H", "Orgrimmar - Vehena (37.8, 87.6)", 1454, 37.8, 87.6 },
            },
        },
    },
    tiers = {
    },
})
