-------------------------------------------------------------------------------
--  Data/Factions/Darnassus.lua -- Darnassus in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Darnassus", {
    id = 69, name = "Darnassus", tab = "reputation",
    group = "Cities",
    zone = "Darnassus",
    side = "Alliance",
    maps = { 1438, 1457 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7801, "A", "Darnassus - Raedon Duskstriker (63.8, 22.8)", 1457, 63.8, 22.8 },
            },
        },
        { name = "Morrowgrain to Darnassus", rep = 50, level = 55, takes = { 11040, 10 },
            quests = {
                { 3803, "A", "Darnassus - Mathrengyl Bearwalker (35.2, 8)", 1457, 35.2, 8 },
            },
        },
        { name = "Morrowgrain to Feathermoon Stronghold", rep = 25, level = 55, takes = { 11040, 5 },
            quests = {
                { 3792, "A", "Feralas - Quintis Jonespyre (32.4, 43.8)", 1444, 32.4, 43.8 },
            },
        },
    },
    tiers = {
    },
})
