-------------------------------------------------------------------------------
--  Data/Factions/DurotarSupplyAndLogistics.lua -- Durotar Supply and Logistics in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("DurotarSupplyAndLogistics", {
    id = 2587, name = "Durotar Supply and Logistics", tab = "reputation",
    zone = "The Barrens",
    new = true,
    quartermaster = { name = "Gishah", map = 1413, x = 49.4, y = 29.4 },
    maps = { 1413 },
    tiers = {
        { standing = 6, items = { 270887 } },
        { standing = 8, items = { 262764 } },
    },
    prices = {
        [262764] = 50000,
    },
})
