-------------------------------------------------------------------------------
--  Data/Factions/Everlook.lua -- Everlook in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Everlook", {
    id = 577, name = "Everlook", tab = "reputation",
    group = "Steamwheedle Cartel",
    zone = "Winterspring",
    quartermaster = { name = "Zippie Fizzbolt", map = 1452, x = 61.4, y = 38.6 },
    maps = { 1452 },
    tiers = {
        { standing = 5, items = { 274755, 274756, 274757, 274758 } },
        { standing = 6, items = { 274759, 274760, 274761 } },
        { standing = 7, items = { 274024 } },
    },
    prices = {
        [274024] = 250000,
        [274755] = 30955,
        [274756] = 58416,
        [274757] = 46779,
        [274758] = 109560,
        [274759] = 75407,
        [274760] = 75687,
        [274761] = 75960,
    },
})
