-------------------------------------------------------------------------------
--  Data/Factions/Gadgetzan.lua -- Gadgetzan in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Gadgetzan", {
    id = 369, name = "Gadgetzan", tab = "reputation",
    group = "Steamwheedle Cartel",
    zone = "Tanaris",
    quartermaster = { name = "Rettrick", map = 1446, x = 51.6, y = 28.6 },
    maps = { 1446 },
    turnins = {
        { name = "Water Pouch Bounty", rep = 10, level = 44, takes = { 8483, 5 },
            quests = {
                { 1878, "B", "Tanaris - Spigot Operator Luglunket (52.4, 28.4)", 1446, 52.4, 28.4 },
            },
            from = {
                { "Tanaris", 6, "Wastewander Assassin", "Wastewander Bandit", "Wastewander Rogue", "Wastewander Scofflaw", "Wastewander Shadow Mage", "Wastewander Thief" },
            },
        },
    },
    tiers = {
        { standing = 5, items = { 274750, 274751, 274752 } },
        { standing = 6, items = { 274753, 274754 } },
        { standing = 7, items = { 274023 } },
    },
    prices = {
        [274023] = 100000,
        [274750] = 27439,
        [274751] = 29423,
        [274752] = 23565,
        [274753] = 94614,
        [274754] = 37989,
    },
})
