-------------------------------------------------------------------------------
--  Data/Factions/GnomereganExiles.lua -- Gnomeregan Exiles in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("GnomereganExiles", {
    id = 54, name = "Gnomeregan Exiles", tab = "reputation",
    group = "Cities",
    zone = "Ironforge",
    side = "Alliance",
    maps = { 1455 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7812, "A", "Ironforge - Bubulo Acerbus (73.8, 47.8)", 1455, 73.8, 47.8 },
            },
        },
    },
    tiers = {
    },
})
