-------------------------------------------------------------------------------
--  Data/Factions/GuardiansOfHyjal.lua -- Guardians of Hyjal in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("GuardiansOfHyjal", {
    id = 2765, name = "Guardians of Hyjal", tab = "reputation",
    zone = "Mount Hyjal",
    new = true,
    quartermaster = { name = "Rhylin Stonethorn", map = 2482, x = 70.6, y = 51.2 },
    maps = { 2482 },
    tiers = {
        { standing = 7, items = { 274379 } },
        { standing = 8, items = { 274025 } },
    },
    prices = {
        [274025] = 250000,
        [274379] = 100000,
    },
})
