-------------------------------------------------------------------------------
--  Data/Factions/HydraxianWaterlords.lua -- Hydraxian Waterlords in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("HydraxianWaterlords", {
    id = 749, name = "Hydraxian Waterlords", tab = "reputation",
    zone = "Azshara",
    unreleased = true,
    maps = { 1447 },
    tiers = {
        { standing = 7, items = { 228979, 22705 } },
    },
    prices = {
        [22705] = 150000,
        [228979] = 100000,
    },
})
