-------------------------------------------------------------------------------
--  Data/Factions/KirinTor.lua -- Kirin Tor in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("KirinTor", {
    id = 2740, name = "Kirin Tor", tab = "reputation",
    zone = "Dalaran",
    new = true,
    quartermaster = { name = "Archmage Alvareaux", map = 1416, x = 14, y = 63.2 },
    maps = { 1416 },
    tiers = {
        { standing = 5, items = { 276984, 276985, 276986, 276987, 276988, 276989, 276990, 276991 } },
        { standing = 8, items = { 285327 } },
    },
    prices = {
        [276984] = 100000,
        [276985] = 100000,
        [276986] = 100000,
        [276987] = 100000,
        [276988] = 100000,
        [276989] = 100000,
        [276990] = 100000,
        [276991] = 100000,
        [285327] = 250000,
    },
})
