-------------------------------------------------------------------------------
--  Data/Factions/Orgrimmar.lua -- Orgrimmar in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Orgrimmar", {
    id = 76, name = "Orgrimmar", tab = "reputation",
    group = "Cities",
    zone = "Orgrimmar",
    side = "Horde",
    maps = { 1454 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7832, "H", "Orgrimmar - Rashona Straglash (63.4, 51)", 1454, 63.4, 51 },
            },
        },
        { name = "Chen's Empty Keg", rep = 50, level = 24, takes = { 4898, 5, 4897, 5, 4896, 1 },
            quests = {
                { 822, "H", "The Barrens - Brewmaster Drohn (62.2, 38.4)", 1413, 62.2, 38.4 },
            },
            from = {
                { "The Barrens", 8, "Barrens Kodo", "Brontus", "Greater Barrens Kodo", "Greater Thunderhawk", "Lakota'mani", "Lost Barrens Kodo" },
            },
        },
    },
    tiers = {
    },
})
