-------------------------------------------------------------------------------
--  Data/Factions/Powderfuse.lua -- Powderfuse in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Powderfuse", {
    id = 2827, name = "Powderfuse", tab = "reputation",
    zone = "Riverglades",
    new = true,
    quartermaster = { name = "Friz Frazzlespark", map = 2548, x = 77, y = 52.8 },
    maps = { 2548 },
    tiers = {
        { standing = 5, items = { 276200, 276201, 276202 } },
        { standing = 6, items = { 276203, 276204 } },
        { standing = 7, items = { 276199 } },
    },
    prices = {
        [276199] = 100000,
        [276200] = 27439,
        [276201] = 29423,
        [276202] = 23565,
        [276203] = 94614,
        [276204] = 37989,
    },
})
