-------------------------------------------------------------------------------
--  Data/Factions/Ratchet.lua -- Ratchet in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Ratchet", {
    id = 470, name = "Ratchet", tab = "reputation",
    group = "Steamwheedle Cartel",
    zone = "The Barrens",
    quartermaster = { name = "Winklespark", map = 1413, x = 62.4, y = 37.6 },
    maps = { 1413 },
    tiers = {
        { standing = 5, items = { 274740, 274741, 274742 } },
        { standing = 6, items = { 274743, 274744 } },
        { standing = 7, items = { 274021 } },
    },
    prices = {
        [274021] = 20000,
        [274740] = 4068,
        [274741] = 5445,
        [274742] = 3442,
        [274743] = 6581,
        [274744] = 16516,
    },
})
