-------------------------------------------------------------------------------
--  Data/Factions/TheWatchers.lua -- The Watchers in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("TheWatchers", {
    id = 2819, name = "The Watchers", tab = "reputation",
    new = true,
    tiers = {
        { standing = 5, items = { 275968, 275969, 275970, 275971 } },
        { standing = 6, items = { 275972, 275973, 275974, 275975, 277519, 277153 } },
        { standing = 7, items = { 275976, 275977, 275979, 275980 } },
        { standing = 8, items = { 275981, 275982, 275983, 275984 } },
    },
    prices = {
        [275968] = 50000,
        [275969] = 50000,
        [275970] = 50000,
        [275971] = 50000,
        [275972] = 80000,
        [275973] = 80000,
        [275974] = 80000,
        [275975] = 80000,
        [275976] = 120000,
        [275977] = 120000,
        [275979] = 120000,
        [275980] = 120000,
        [275981] = 200000,
        [275982] = 200000,
        [275983] = 200000,
        [275984] = 200000,
        [277153] = 2000000,
        [277519] = 100000,
    },
})
