-------------------------------------------------------------------------------
--  Data/Factions/ThoriumBrotherhood.lua -- Thorium Brotherhood in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("ThoriumBrotherhood", {
    id = 59, name = "Thorium Brotherhood", tab = "reputation",
    zone = "Blackrock Depths",
    dungeons = { "BlackrockDepths" },
    maps = { 1427 },
    turnins = {
        { name = "Gaining Acceptance", rep = 25, level = 60, takes = { 18945, 4 },
            quests = {
                { 7737, "B", "Searing Gorge - Master Smith Burninate (38.6, 28.4)", 1427, 38.6, 28.4 },
            },
        },
        { name = "Restoring Fiery Flux Supplies via Kingsblood", rep = 25, level = 60, takes = { 18944, 2, 3356, 2, 3857, 4 },
            quests = {
                { 7736, "B", "Searing Gorge - Master Smith Burninate (38.6, 28.4)", 1427, 38.6, 28.4 },
            },
            from = {
                { "Searing Gorge", 10, "Blazing Elemental", "Duke Searbrand", "Firelands Drudge", "Firelands Invader", "Incendosaur", "Inferno Elemental" },
            },
        },
        { name = "Restoring Fiery Flux Supplies via Iron", rep = 25, level = 60, takes = { 18944, 2, 3575, 2, 3857, 4 },
            quests = {
                { 8241, "B", "Searing Gorge - Master Smith Burninate (38.6, 28.4)", 1427, 38.6, 28.4 },
            },
            from = {
                { "Searing Gorge", 9, "Blazing Elemental", "Duke Searbrand", "Firelands Drudge", "Firelands Invader", "Incendosaur", "Inferno Elemental" },
                { "The Barrens", 1, "Fel Interloper" },
                { "Redridge Mountains", 1, "Fel Interloper" },
                { "Ashenvale", 1, "Fel Interloper" },
                { "Swamp of Sorrows", 1, "Fel Interloper" },
                { "Desolace", 1, "Fel Interloper" },
                { "Blasted Lands", 1, "Fel Interloper" },
                { "Azshara", 1, "Fel Interloper" },
                { "Feralas", 1, "Fel Interloper" },
            },
        },
        { name = "Restoring Fiery Flux Supplies via Heavy Leather", rep = 25, level = 60, takes = { 18944, 2, 4234, 2, 3857, 10 },
            quests = {
                { 8242, "B", "Searing Gorge - Master Smith Burninate (38.6, 28.4)", 1427, 38.6, 28.4 },
            },
            from = {
                { "Searing Gorge", 10, "Blazing Elemental", "Duke Searbrand", "Firelands Drudge", "Firelands Invader", "Incendosaur", "Inferno Elemental" },
            },
        },
        { name = "Favor Amongst the Brotherhood, Dark Iron Ore", rep = 50, level = 60, takes = { 11370, 10 },
            quests = {
                { 6642, "B", "Blackrock Depths - Lokhtos Darkbargainer" },
            },
            from = {
                { "Blackrock Depths", 7, "Marshal Windsor", "Molten War Golem", "Panzor the Invincible", "Phalanx", "Ragereaver Golem", "Warbringer Construct" },
            },
        },
        { name = "Favor Amongst the Brotherhood, Core Leather", rep = 150, level = 60, takes = { 17012, 2 },
            quests = {
                { 6645, "B", "Blackrock Depths - Lokhtos Darkbargainer" },
            },
        },
        { name = "Favor Amongst the Brotherhood, Fiery Core", rep = 200, level = 60, takes = { 17010, 1 },
            quests = {
                { 6643, "B", "Blackrock Depths - Lokhtos Darkbargainer" },
            },
        },
        { name = "Favor Amongst the Brotherhood, Lava Core", rep = 200, level = 60, takes = { 17011, 1 },
            quests = {
                { 6644, "B", "Blackrock Depths - Lokhtos Darkbargainer" },
            },
        },
        { name = "Favor Amongst the Brotherhood, Blood of the Mountain", rep = 200, level = 60, takes = { 11382, 1 },
            quests = {
                { 6646, "B", "Blackrock Depths - Lokhtos Darkbargainer" },
            },
        },
    },
    tiers = {
        { standing = 5, items = { 17051, 17018, 17023, 20761, 17022, 19444 } },
        { standing = 6, items = { 17059, 17060, 17049, 229008, 229009, 19206, 19219, 19330, 19448, 17017, 17025 } },
        { standing = 7, items = { 17053, 17052, 19207, 19220, 19331, 19332, 19333, 19449, 19208, 19209 } },
        { standing = 8, items = { 19210, 19211, 19212, 20040 } },
    },
    prices = {
        [17017] = 180000,
        [17018] = 80000,
        [17022] = 150000,
        [17023] = 160000,
        [17025] = 160000,
        [17049] = 90000,
        [17051] = 70000,
        [17052] = 180000,
        [17053] = 200000,
        [17059] = 220000,
        [17060] = 220000,
        [19206] = 60000,
        [19207] = 80000,
        [19208] = 70000,
        [19209] = 70000,
        [19210] = 120000,
        [19211] = 120000,
        [19212] = 120000,
        [19219] = 60000,
        [19220] = 90000,
        [19330] = 60000,
        [19331] = 90000,
        [19332] = 90000,
        [19333] = 90000,
        [19444] = 30000,
        [19448] = 80000,
        [19449] = 100000,
        [20040] = 80000,
        [20761] = 120000,
        [229008] = 100000,
        [229009] = 100000,
    },
})
