-------------------------------------------------------------------------------
--  Data/Factions/TimbermawHold.lua -- Timbermaw Hold in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("TimbermawHold", {
    id = 576, name = "Timbermaw Hold", tab = "reputation",
    zone = "Felwood",
    quartermaster = { name = "Meilosh", map = 1448, x = 65.4, y = 2.8 },
    maps = { 1448, 1452 },
    turnins = {
        { name = "Feathers for Grazle", rep = 50, level = 55, takes = { 21377, 5 },
            quests = {
                { 8466, "B", "Felwood - Grazle (51, 85)", 1448, 51, 85 },
            },
            from = {
                { "Felwood", 10, "Chieftain Bloodmaw", "Cleansed Songflower", "Deadwood Avenger", "Deadwood Den Watcher", "Deadwood Gardener", "Deadwood Pathfinder" },
            },
        },
        { name = "Feathers for Nafien", rep = 50, level = 55, takes = { 21377, 5 },
            quests = {
                { 8467, "B", "Felwood - Nafien (64.8, 8.2)", 1448, 64.8, 8.2 },
            },
            from = {
                { "Felwood", 10, "Chieftain Bloodmaw", "Cleansed Songflower", "Deadwood Avenger", "Deadwood Den Watcher", "Deadwood Gardener", "Deadwood Pathfinder" },
            },
        },
        { name = "Beads for Salfa", rep = 50, level = 56, takes = { 21383, 5 },
            quests = {
                { 8469, "B", "Winterspring - Salfa (27.8, 34.4)", 1452, 27.8, 34.4 },
            },
            from = {
                { "Winterspring", 7, "High Chief Winterfall", "Winterfall Den Watcher", "Winterfall Pathfinder", "Winterfall Runner", "Winterfall Shaman", "Winterfall Totemic" },
            },
        },
    },
    tiers = {
        { standing = 5, items = { 13484, 22392, 20254, 20253 } },
        { standing = 6, items = { 19202, 19215, 19326, 19445 } },
        { standing = 7, items = { 228982, 251469, 251470, 19204, 19218, 19327 } },
        { standing = 8, items = { 21326 } },
    },
    prices = {
        [13484] = 15000,
        [19202] = 22000,
        [19204] = 40000,
        [19215] = 22000,
        [19218] = 40000,
        [19326] = 22000,
        [19327] = 40000,
        [19445] = 30000,
        [20253] = 16000,
        [20254] = 20000,
        [21326] = 35965,
        [22392] = 25000,
        [228982] = 100000,
        [251469] = 100000,
        [251470] = 100000,
    },
})
