-------------------------------------------------------------------------------
--  Data/Factions/Undercity.lua -- Undercity in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("Undercity", {
    id = 68, name = "Undercity", tab = "reputation",
    group = "Cities",
    zone = "Undercity",
    side = "Horde",
    maps = { 1458 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7819, "H", "Undercity - Ralston Farnsley (71.6, 28.8)", 1458, 71.6, 28.8 },
            },
        },
    },
    tiers = {
    },
})
