-------------------------------------------------------------------------------
--  Data/Factions/ZandalarTribe.lua -- Zandalar Tribe in the Dungeon Journal.
--  Generated by Tools/build_factions.py from Tools/journal_factions.json and the game's
--  item tables (build 1.60.1.70205); do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddFaction("ZandalarTribe", {
    id = 270, name = "Zandalar Tribe", tab = "reputation",
    zone = "Stranglethorn Vale",
    unreleased = true,
    maps = { 1434 },
    tiers = {
        { standing = 5, items = { 19766, 19771, 19778, 19781, 20001, 20757, 20012 } },
        { standing = 6, items = { 19765, 19770, 19773, 19777, 19780, 20000, 20756, 232610, 20014 } },
        { standing = 7, items = { 19764, 19769, 19772, 19776, 19779, 20011 } },
        { standing = 8, items = { 20013 } },
    },
    prices = {
        [19764] = 50000,
        [19765] = 50000,
        [19766] = 50000,
        [19769] = 50000,
        [19770] = 50000,
        [19771] = 50000,
        [19772] = 50000,
        [19773] = 50000,
        [19776] = 50000,
        [19777] = 50000,
        [19778] = 50000,
        [19779] = 50000,
        [19780] = 50000,
        [19781] = 50000,
        [20000] = 120000,
        [20001] = 50000,
        [20011] = 50000,
        [20012] = 50000,
        [20013] = 50000,
        [20014] = 50000,
        [20756] = 40000,
        [20757] = 40000,
        [232610] = 40000,
    },
})
