-------------------------------------------------------------------------------
--  Data/Dungeons/Stockade.lua -- The Stockade in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Stockade", {
    name = "The Stockade",
    zone = "Stormwind City", territory = "Alliance",
    entrance = { map = 1453, x = 51.0, y = 68.1 },
    wings = {
        { bosses = {
            { npc = 1696, name = "Targorr the Dread", model = 517, encounters = { 2756 }, loot = { 273804, 273805, 273806 } },
            { npc = 1666, name = "Kam Deepfury", model = 825, encounters = { 2757 }, loot = { 2280, 273807, 273808 }, chance = { 1, 0, 0 } },
            { npc = 1717, name = "Hamhock", model = 3250, encounters = { 2758 }, loot = { 273809, 273810, 273811 } },
            { npc = 1716, name = "Bazil Thredd", model = 1621, encounters = { 2760 }, loot = { 273824, 273825, 273827, 273829 } },
            { npc = 1663, name = "Dextren Ward", model = 2149, encounters = { 2759 }, loot = { 273817, 273819, 273820 } },
            { npc = 1720, name = "Bruegal Ironknuckle", model = 2142, rare = true, loot = { 3228, 2941, 2942 }, chance = { 56, 19, 18 } },
            { npc = nil, name = "Trash", trash = true, loot = { 1076, 274092 } },
        } },
    },
})
